POST  {{url}}/auth/sign-up
Content-Type: application/json

{
  "firstName": "Aung Zayar Moe",
  "lastName": "One",
  "username": "Swanhtet12@",
  "email": "son775697@gmail.com",
  "password": "SecureP@ssw0rd!",
  "country": "United State USA",
  "bioMetricHash": "a94a8fe5ccb19ba61c4c0873d391e987982fbbd3"
}

### POST Confirm email
POST  {{url}}/auth/verify-email
Content-Type: application/json

{
  "email": "son775697@gmail.com",
  "code": "308448"
}

### POST Sign In
POST {{url}}/auth/sign-in
Content-Type: application/json

{
  "email": "swanhtetaungp@gmail.com",
  "password": "SecureP@ssw0rd!"
}

### POST Log Out
POST {{url}}/auth/log-out
Authorization: {{claim_access}}